services:
    web:
      build: 
        context: ./backend
        dockerfile: Dockerfile
      container_name: web
      env_file:
        - prod.env
      ports: "8000:8000"
      restart: always
      volumes:
        - static_volume:/app/static
      depends_on:
        - postgres
    postgres:
        image: 'postgres:17'
        container_name: postgres
        restart: always
        env_file:
          - dev.env
        ports:
          - "5433:5432"
        volumes:
          - db_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
  static_volume: