# Generated by Django 6.0.2 on 2026-03-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_todo_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(default="#ff0000", max_length=7),
        ),
    ]
